# Generated by Django 2.2 on 2019-05-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_img',
            field=models.ImageField(blank=True, null=True, upload_to='answer_img'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='question_img'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_listen',
            field=models.FileField(blank=True, null=True, upload_to='question_listen'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_sub',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
