# Generated by Django 2.2 on 2019-04-04 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0002_auto_20190404_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MODELNAME',
            new_name='Answer',
        ),
    ]
