# Generated by Django 2.2 on 2019-04-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0003_auto_20190404_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(default='student/images/default_avatar.png', max_length=255),
        ),
    ]
