# Generated by Django 2.2 on 2019-04-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0004_userinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='student/images/default_avatar.png', upload_to=''),
        ),
    ]
