# Generated by Django 2.2 on 2019-04-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0005_auto_20190406_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='/avatar_user/default_avatar.png', upload_to=''),
        ),
    ]
