# Generated by Django 2.2 on 2019-04-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0006_auto_20190406_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_img',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_listen',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
