# Generated by Django 2.2 on 2019-04-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0007_auto_20190406_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(default='/static/student/images/default_avatar.png', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
