# Generated by Django 2.2 on 2019-04-08 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0010_auto_20190408_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='user',
        ),
        migrations.AddField(
            model_name='exam_question',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_exam.List_User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='exam_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_exam.Exam_Question'),
        ),
    ]
