# Generated by Django 2.2 on 2019-04-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0011_auto_20190408_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='result_slug',
        ),
        migrations.AddField(
            model_name='result',
            name='rank',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
