# Generated by Django 2.2 on 2019-04-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0016_result_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='key',
        ),
        migrations.AddField(
            model_name='exam_result',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
