# Generated by Django 2.2 on 2019-04-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0018_result_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_suggest',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
