# Generated by Django 2.2 on 2019-04-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0019_question_question_suggest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_suggest',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
