# Generated by Django 2.2 on 2019-04-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0021_auto_20190420_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_main',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_sub',
            field=models.TextField(blank=True),
        ),
    ]
