# Generated by Django 2.2 on 2019-04-22 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0022_auto_20190420_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='batch_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='exam_slug',
            new_name='slug',
        ),
    ]
