# Generated by Django 2.2 on 2019-04-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0023_auto_20190422_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam_result',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='admin_exam.List_User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
