# Generated by Django 2.2 on 2019-04-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0024_auto_20190424_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='choose_answer',
            field=models.IntegerField(default=0),
        ),
    ]
