# Generated by Django 2.2 on 2019-04-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0025_auto_20190424_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
