# Generated by Django 2.2 on 2019-04-25 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0026_batch_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
