# Generated by Django 2.2 on 2019-04-27 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0028_auto_20190427_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
    ]
