# Generated by Django 2.2 on 2019-04-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0031_auto_20190428_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='created_date',
            field=models.CharField(default='28/04/2019 11:55', max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='time_from',
            field=models.CharField(default='28/04/2019 11:55', max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='time_to',
            field=models.CharField(default='28/04/2019 11:55', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam_result',
            name='date',
            field=models.CharField(default='28/04/2019 11:55', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_day',
            field=models.DateField(default='28/04/2019 11:55'),
        ),
    ]
