# Generated by Django 2.2 on 2019-04-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exam', '0032_auto_20190428_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='created_date',
            field=models.DateTimeField(default='2019-04-28 12:33'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='time_from',
            field=models.DateTimeField(default='2019-04-28 12:33'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='time_to',
            field=models.DateTimeField(default='2019-04-28 12:33'),
        ),
        migrations.AlterField(
            model_name='exam_result',
            name='date',
            field=models.CharField(default='28/04/2019 12:33', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birth_day',
            field=models.DateField(),
        ),
    ]
